### ISSUE TITLE
Skew pulsar-output of filebeat

### ISSUE THREAD

**Issue by thinker0** [streamnative/pulsar-beat-output#24]
Skew Producer
![image](https://user-images.githubusercontent.com/357785/89148568-2e309280-d595-11ea-8e9b-3fea835100b7.png)

**Comment by wolfstudy** [comment]
@thinker0 Can you help to update the pulsar-client-go version?

**Comment by thinker0** [comment]
can't build.

**Comment by codelipenghui** [comment]
@thinker0 Could you please provide more details? error log or others.

**Comment by thinker0** [comment]
@codelipenghui 

```
filebeat:
  inputs:
    -
      paths:
        - {{profile.logDesc.paths}}
      fields:
        type: {{profile.logDesc.doc_type}}
        env: {{profile.env}}
        source: {{profile.logDesc.source}}
        cluster: {{profile.cluster}}
        region: {{profile.logDesc.region}}
      encoding: utf-8
      close_timeout: 30m
      tail_files: true
      document_type: {{profile.logDesc.doc_type}}
      json.keys_under_root: true
      json.add_error_key: true
    -
      paths:
        - {{profile.logDesc.errors}}
        - /var/log/nginx/error_log
        - /var/log/nginx/nginx_error_log
      fields:
        type: {{profile.logDesc.doc_type}}
        env: {{profile.env}}
        source: nginx-error
        cluster: {{profile.cluster}}
        region: {{profile.logDesc.region}}
      encoding: utf-8
      tail_files: true
      document_type: {{profile.logDesc.doc_type}}
  registry.migrate_file: /home/{{profile.role}}/.filebeat/.filebeat-{{profile.logDesc.doc_type}}
  registry.path: /home/{{profile.role}}/.filebeat/.filebeat7-{{profile.logDesc.doc_type}}

output.pulsar:
  url: pulsar://lad-pulsar:26650
  topic: {{profile.logDesc.kafka_topic}}
  name: filebeat-pulsar-{{profile.logDesc.kafka_topic}}
  block_if_queue_full: true
  compression_type: 3
```

A normal message is output and there is no error log.
