### ISSUE TITLE
Conditional topic selection

### ISSUE THREAD

**Issue by cagucor** [streamnative/pulsar-beat-output#64]
Hi Everyone,

Is there a way to conditionally apply a topic to a certain message? For example: if an object has a field like level, then it will be published to a different topic if it is an info or warning.

**Comment by hezhangjian** [comment]
@SperChung-11 Could you please look at this issue, thank you :)

**Comment by SperChung-11** [comment]
hi, @cagucor. you can try filebeat.yml config as follows :

```
filebeat.inputs:
- type: log
  enabled: true
  paths: /var/log/message
  fields:
    log_topic: warn_topic
  include_lines: ['WARN']

- type: log
  enabled: true
  paths: /var/log/message
  fields:
    log_topic: info_topic
  include_lines: ['INFO']

#--------------------------pulsar  output ------------------------------
output.pulsar:
  enabled: true
  url: ${PULSAR_ADDRESS}
  topic: '%{[fields.log_topic]}'
```
